### ISSUE TITLE
Permission denied in Windows 7

### ISSUE THREAD

**Issue by CarlosAmaral** [endel/increase-memory-limit#13]
When I run `increase-memory-limit` I get the full path of the installed module with a `: Permission denied`

Thank you!

Carlos

**Comment by nicoesiea** [comment]
Did you try to open your command prompt in admin mode ?

**Comment by endel** [comment]
This library has been deprecated. Please use Node.js v8+ and set `NODE_OPTIONS` environment variable. (https://github.com/endel/increase-memory-limit#deprecation-notice)
