### ISSUE TITLE
not working within a docker with ubuntu

### ISSUE THREAD

**Issue by jcabrerazuniga** [endel/increase-memory-limit#14]
I am using a docker image created with:

FROM ubuntu:16.04
MAINTAINER Jose

# Environment variables
ENV SBT_VERSION		0.13.13
ENV SBT_HOME		/usr/local/sbt
ENV SCALA_VERSION	2.11.8
ENV SCALA_HOME		/usr/local/scala
ENV NPM_HOME	    /root/.nvm/versions/node/v8.9.0
ENV PATH		$SCALA_HOME/bin:$SBT_HOME/bin:$NPM_HOME/bin:$PATH
ENV NVM_DIR=/root/.nvm
ENV SHIPPABLE_NODE_VERSION=v8.9.0

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean
	
RUN apt-get install apt-transport-https
RUN apt-get install bc
RUN apt-get install curl
RUN apt-get install nano
RUN apt-get install -y python2.7

RUN apt-get remove scala-library scala
RUN wget www.scala-lang.org/files/archive/scala-2.11.8.deb
RUN dpkg -i scala-2.11.8.deb

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
RUN apt-get update
RUN apt-get install -y sbt
RUN apt-get install -y mc

RUN apt-get install -y build-essential libssl-dev
RUN curl -sL https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh -o install_nvm.sh
RUN bash install_nvm.sh

RUN . $HOME/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
RUN mkdir /application

RUN npm config set python /usr/bin/python2.7
RUN npm config set python2 /usr/bin/python2.7

and after I install your add on and if I run your command to increase memory, and 
         run npm watch build
my ubuntu docker image hangs.
Any ideas why?
Thx

**Comment by rwdalpe** [comment]
Probably because of #2

**Comment by endel** [comment]
This library has been deprecated. Please use Node.js v8+ and set `NODE_OPTIONS` environment variable. (https://github.com/endel/increase-memory-limit#deprecation-notice)
