### ISSUE TITLE
How to run on Window10?

### ISSUE THREAD

**Issue by nicoesiea** [endel/increase-memory-limit#17]
Using Windows10, when I start my test, I get the error message:

> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

That why I'm trying to use this code. 
First, I use the command line to install the package:
`$ npm install -g increase-memory-limit`
The result was:
`P:\...\profiles\...\Application Data\npm\increase-memory-limit`
`P:\...\profiles\...\Application Data\npm\node_modules\increase-memory-limit\index.js`
`P:\...\profiles\...\Application Data\npm`
`-- increase-memory-limit@1.0.6`

But, by entering the command:
`$ increase-memory-limit`
The result is:
`bash: increase-memory-limit: command not found`

By entering the command:
`$ npm increase-memory-limit`
The result is:
`Usage: npm <command>`

In the HOME repository and in my project repository...
How I can apply this fix please?

**Comment by nicoesiea** [comment]
node version is v6.11.5
npm version is 4.2.0

Where can I confirm the installation is correctly done? Where is the folder to control if the new files are well downloaded?

**Comment by endel** [comment]
This library has been deprecated. Please use Node.js v8+ and set `NODE_OPTIONS` environment variable. (https://github.com/endel/increase-memory-limit#deprecation-notice)
