### ISSUE TITLE
node --max-old-space-size=2048 不是内部或外部命令，也不是可运行的程序或批处理文件

### ISSUE THREAD

**Issue by CaoLeilei** [endel/increase-memory-limit#28]
环境：win 10
node：8.9
npm：6.13
vue：2.0

当我执行了cross-env LIMIT=4096 increase-memory-limit 之后，在运行npm run dev 之后，在控制台给暴力如上所描述的错误

**Comment by yqwang0802** [comment]
> 环境：win 10
> node：8.9
> npm：6.13
> vue：2.0
> 
> 当我执行了cross-env LIMIT=4096 increase-memory-limit 之后，在运行npm run dev 之后，在控制台给暴力如上所描述的错误

**Comment by yqwang0802** [comment]
楼主后面怎么解决的？我也碰到同样的问题。

**Comment by wkylin** [comment]
同问，是怎么解决呢？？

**Comment by Alarikshaw** [comment]
如果可以的话 ，请联系我，我也没有解决

**Comment by benleilei** [comment]
os: Window 10
在 \node_modules\.bin 下的 *.cmd 文件中

在 ENDLOCAL 语句的上边一句

修改【"%_prog%"】 为 【%_prog%】，即去掉双引号
