### ISSUE TITLE
' " Node --max-old-space-size=10240" ' is not an internal or external command, nor is it a runnable program or batch files.

### ISSUE THREAD

**Issue by snowIceg** [endel/increase-memory-limit#31]
OS:        Windows 7 ultimate with sp1
Node:    v12.16.2
Vue:       v2.6.11
Vue-cli:   v4.3.1

I follow the README.md. But when I run the command  "npm run serve", the error occurred. The error info is the title of this issue.  I read the comments on a closed issue below and I changed the parameter on one line above "ENDLOCAL" in all files with the suffix "cmd" under \node_modules.bin.
Modify ["%_prog%"] to [%_prog%] ，just remove the double quotation marks.
Problem solved！！！
I think  it's a bug because I must change all of  *.cmd files。 So I want the author to solve this problem。Thanks

=========================================================
os: Window 10
在 \node_modules\.bin 下的 *.cmd 文件中

在 ENDLOCAL 语句的上边一句

修改【"%_prog%"】 为 【%_prog%】，即去掉双引号

_Originally posted by @benleilei in https://github.com/endel/increase-memory-limit/issues/28#issuecomment-632976184_

**Comment by CMRdev** [comment]
I have the same problem
