### ISSUE TITLE
Possible to run from npm task?

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [endel/increase-memory-limit#6]
I'm having trouble figuring out how to integrate this with my npm tasks. Was hoping each dev wouldn't have to run this for each project, but instead to add a call to it to my build-prod task so this runs first. Also need to override the limit as my app needs 1200+. Any help appreciated!

**Comment by endel** [comment]
Hey @PTC-JoshuaMatthews,

You can do something like this:

```
  "scripts": {
    "fix-memory-limit": "cross-env LIMIT=2048 increase-memory-limit"
  },
  "devDependencies": {
    "increase-memory-limit": "^1.0.3",
    "cross-env": "^5.0.5",
  }
```

```
npm run fix-memory-limit
```

**Comment by endel** [comment]
Added these instructions to the README. Feel free to re-open this issue if you'd like to.

**Comment by snapnurse-joshuamatthews** [comment]
Very slick! Thank you!
